version: '3.7'
services:
  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      edu-network:

  web:
    container_name: core_app
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000"
    volumes:
     - .:/app
     - static_volume:/app/static
    networks:
      edu-network:

volumes:
  static_volume:
networks:
  edu-network:
    driver: bridge
