# Generated by Django 3.2.6 on 2021-11-18 07:24

import apps.core.fields
import apps.core.validators
import apps.institute.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('contact', apps.core.fields.PhoneNumberField(max_length=20)),
                ('category', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('established', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('website', models.URLField()),
                ('logo', models.ImageField(default='consultancy/logo/default_logo.png', upload_to=apps.institute.utils.upload_institute_staff_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('cover_image', models.ImageField(default='consultancy/cover_image/default_cover_image.png', upload_to=apps.institute.utils.upload_institute_staff_image_to, validators=[apps.core.validators.ImageValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstituteStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(default='institute_staff/photo/default_logo.png', upload_to=apps.institute.utils.upload_institute_staff_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffposition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.instituteuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
