# Generated by Django 3.2.6 on 2021-12-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScholorshipScheme',
        ),
        migrations.AddField(
            model_name='institute',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
