# Generated by Django 3.2.6 on 2021-12-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmedialink',
            unique_together={('institute', 'name')},
        ),
    ]
