# Generated by Django 3.2.6 on 2021-12-03 05:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20211203_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteScholorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
