# Generated by Django 3.2.6 on 2022-01-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_addinstitutefacility_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='type',
            field=models.TextField(blank=True, choices=[('PUBLIC', 'public'), ('PEIVATE', 'private')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addinstitutefacility',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_related', to='institute.institute'),
        ),
    ]
