# Generated by Django 3.2.6 on 2021-12-08 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_institute_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
