# Generated by Django 3.2.6 on 2022-04-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20220110_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='email',
            new_name='institute_email',
        ),
    ]
