# Generated by Django 3.2.6 on 2022-04-25 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_rename_email_institute_institute_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
