# Generated by Django 3.2.6 on 2021-12-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_alter_institute_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
