# Generated by Django 3.2.6 on 2021-12-24 11:40

import apps.core.generics
import apps.institute.mixins
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_institute_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInstituteView',
            fields=[
                ('institute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='institute.institute')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.generics.RetrieveAPIView, 'institute.institute', apps.institute.mixins.InstituteMixins),
        ),
        migrations.AlterField(
            model_name='institute',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(choices=[('facebook', 'facebook'), ('youtube', 'youtube'), ('linkdin', 'linkdin'), ('instagram', 'instagram')], max_length=100)),
                ('link', models.URLField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
