# Generated by Django 3.2.6 on 2021-12-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute_course', '0001_initial'),
        ('institute', '0001_initial'),
        ('students', '0001_initial'),
        ('consultancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteapply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.faculty'),
        ),
        migrations.AddField(
            model_name='commentapplicationinstitute',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.instituteapply'),
        ),
        migrations.AddField(
            model_name='commentapplicationinstitute',
            name='institute_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institutestaff'),
        ),
        migrations.AddField(
            model_name='commentapplicationconsultancy',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.instituteapply'),
        ),
        migrations.AddField(
            model_name='commentapplicationconsultancy',
            name='consultancy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff'),
        ),
        migrations.AlterUniqueTogether(
            name='institutecourse',
            unique_together={('course', 'institute')},
        ),
        migrations.AlterUniqueTogether(
            name='instituteapply',
            unique_together={('student', 'course')},
        ),
    ]
