# Generated by Django 3.2.6 on 2021-11-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.faculty'),
        ),
        migrations.AlterField(
            model_name='institutecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.course'),
        ),
        migrations.AlterField(
            model_name='institutecourse',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.faculty'),
        ),
    ]
