# Generated by Django 3.2.6 on 2022-01-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20220110_0950'),
        ('institute_course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutecourse',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_related', to='institute.institute'),
        ),
    ]
