# Generated by Django 3.2.6 on 2021-12-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_institutescholorship'),
        ('institute_course', '0002_auto_20211127_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutecourse',
            unique_together={('course', 'institute')},
        ),
    ]
