# Generated by Django 3.2.6 on 2022-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('institute_course', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessofacademicdocument',
            unique_together={('course', 'academic')},
        ),
    ]
