# Generated by Django 3.2.6 on 2022-02-18 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20220110_0950'),
        ('institute_course', '0003_alter_institutecourse_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddScholorshipInCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.institutecourse')),
                ('scholorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institutescholorship')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
