# Generated by Django 3.2.6 on 2021-12-03 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0001_initial'),
        ('institute', '0003_institutescholorship'),
        ('students', '0012_alter_completeprofiletracker_student'),
        ('institute_course', '0003_alter_institutecourse_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteApply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('verify', 'verify'), ('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending'), ('applied', 'applied')], default='pending', max_length=20)),
                ('action_data', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('view_date', models.DateField(blank=True, null=True)),
                ('forward', models.BooleanField()),
                ('action_consultancy_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancystaff')),
                ('action_institute_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.institutestaff')),
                ('consultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancy')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CommentApplicationInstitute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.instituteapply')),
                ('institute_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institutestaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentApplicationConsultancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.instituteapply')),
                ('consultancy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancystaff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
