# Generated by Django 3.2.6 on 2022-05-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0002_initial'),
        ('institute_course', '0003_alter_accessofacademicdocument_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessstudentessay',
            unique_together={('course', 'essay')},
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentidentity',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentlor',
            unique_together={('course', 'lor')},
        ),
        migrations.AlterUniqueTogether(
            name='accessstudentsop',
            unique_together={('course', 'sop')},
        ),
    ]
