# Generated by Django 3.2.6 on 2021-12-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0004_commentapplicationconsultancy_commentapplicationinstitute_instituteapply'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instituteapply',
            unique_together=set(),
        ),
    ]
