# Generated by Django 3.2.6 on 2022-04-30 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20220427_1451'),
        ('studentIdentity', '0002_initial'),
        ('institute_course', '0005_auto_20220427_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessStudentSop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studentsop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessStudentLor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse')),
                ('lor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studentlor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessStudentIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentIdentity.citizenship')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse')),
                ('passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentIdentity.passport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessStudentEssay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse')),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.personalessay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessOfAcademicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.academic')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_course.institutecourse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
