# Generated by Django 3.2.6 on 2021-12-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_completeprofiletracker_student'),
        ('institute_course', '0006_alter_instituteapply_forward'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instituteapply',
            unique_together={('student', 'course')},
        ),
    ]
