# Generated by Django 3.2.6 on 2022-05-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0006_accessofacademicdocument_accessstudentessay_accessstudentidentity_accessstudentlor_accessstudentsop'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutecourse',
            name='academic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutecourse',
            name='citizenship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutecourse',
            name='essay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutecourse',
            name='lor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutecourse',
            name='passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutecourse',
            name='sop',
            field=models.BooleanField(default=False),
        ),
    ]
