# Generated by Django 3.2.6 on 2022-05-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentmodel_dob'),
        ('institute_course', '0007_auto_20220501_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessofacademicdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessstudentessay',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessstudentidentity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessstudentlor',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
        migrations.AddField(
            model_name='accessstudentsop',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
    ]
