# Generated by Django 3.2.6 on 2021-12-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0007_alter_instituteapply_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteapply',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instituteapply',
            name='action',
            field=models.CharField(choices=[('verify', 'verify'), ('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending'), ('applied', 'applied')], default='applied', max_length=20),
        ),
    ]
