# Generated by Django 3.2.6 on 2021-12-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_favouriteinstitute'),
        ('institute', '0006_alter_institute_email'),
        ('consultancy', '0001_initial'),
        ('institute_course', '0008_auto_20211214_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentapplicationconsultancy',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.instituteapply'),
        ),
        migrations.AlterField(
            model_name='commentapplicationconsultancy',
            name='consultancy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff'),
        ),
        migrations.AlterField(
            model_name='commentapplicationinstitute',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.instituteapply'),
        ),
        migrations.AlterField(
            model_name='commentapplicationinstitute',
            name='institute_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institutestaff'),
        ),
        migrations.AlterField(
            model_name='instituteapply',
            name='action_consultancy_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancystaff'),
        ),
        migrations.AlterField(
            model_name='instituteapply',
            name='action_institute_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institutestaff'),
        ),
        migrations.AlterField(
            model_name='instituteapply',
            name='consultancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy.consultancy'),
        ),
        migrations.AlterField(
            model_name='instituteapply',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute_course.institutecourse'),
        ),
        migrations.AlterField(
            model_name='instituteapply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentmodel'),
        ),
    ]
