# Generated by Django 3.2.6 on 2022-05-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_course', '0008_auto_20220501_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessofacademicdocument',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_student_academic', to='institute_course.institutecourse'),
        ),
        migrations.AlterField(
            model_name='accessstudentidentity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_student_identity', to='institute_course.institutecourse'),
        ),
    ]
