# Generated by Django 3.2.6 on 2022-04-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentmodel_dob'),
        ('institute', '0006_alter_institute_institute_email'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutereview',
            unique_together={('student', 'institute')},
        ),
    ]
