# Generated by Django 3.2.6 on 2021-11-16 17:33

import apps.core.validators
import apps.students.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='image',
            field=models.ImageField(default='student/image/default_logo.png', upload_to=apps.students.utils.upload_student_image_to, validators=[apps.core.validators.ImageValidator()]),
        ),
    ]
