# Generated by Django 3.2.6 on 2022-01-07 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_addinstitutefacility_facility'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIdCreator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='studentaddress',
            name='student',
            field=models.OneToOneField(error_messages={'unique': 'address of the user already exist'}, on_delete=django.db.models.deletion.CASCADE, related_name='address_relation', to='students.studentmodel'),
        ),
        migrations.CreateModel(
            name='InstituteVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institute')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.visitoridcreator')),
            ],
            options={
                'unique_together': {('visitor', 'institute')},
            },
        ),
    ]
