# Generated by Django 3.2.6 on 2021-11-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211128_0407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryAddress',
        ),
    ]
