# Generated by Django 3.2.6 on 2022-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220107_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
