# Generated by Django 3.2.6 on 2022-05-01 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_institute_rating'),
        ('students', '0003_studentmodel_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteViewers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
            options={
                'unique_together': {('student', 'institute')},
            },
        ),
        migrations.DeleteModel(
            name='InstituteVisitor',
        ),
        migrations.DeleteModel(
            name='VisitorIdCreator',
        ),
    ]
