# Generated by Django 3.2.6 on 2021-11-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_temporaryaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PermanentAddress',
            new_name='StudentAddress',
        ),
    ]
