# Generated by Django 3.2.6 on 2021-11-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_permanentaddress_studentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_academic_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_citizenship_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_lor_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_parents_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_passport_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_personalessay_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='complete_sop_field',
            field=models.BooleanField(default=False),
        ),
    ]
