# Generated by Django 3.2.6 on 2021-11-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211128_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaddress',
            name='student',
            field=models.OneToOneField(error_messages={'unique': 'address of the user already exist'}, on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel'),
        ),
    ]
