# Generated by Django 3.2.6 on 2021-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentaddress_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='fullname',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
