# Generated by Django 3.2.6 on 2021-11-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentmodel_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
