# Generated by Django 3.2.6 on 2021-11-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20211130_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeprofiletracker',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_tracker', to='students.studentmodel'),
        ),
    ]
