# Generated by Django 3.2.6 on 2021-12-16 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_institute_email'),
        ('students', '0012_alter_completeprofiletracker_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteInstitute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.studentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
