# Generated by Django 3.2.6 on 2021-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyotp', '0002_pyotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyotp',
            name='purpose',
            field=models.CharField(choices=[('R', 'PasswordReset'), ('A', 'Activation'), ('P', 'PhoneNumberVerification'), ('E', 'EmailVerification'), ('2FA', 'TwoFactorAuthentication')], help_text='Purpose of OTP.', max_length=3, verbose_name='Purpose'),
        ),
    ]
