# Generated by Django 3.2.6 on 2022-01-10 09:50

import apps.blog.utils
import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20220110_0950'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteBlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='consultancy/logo/default_logo.png', upload_to=apps.blog.utils.upload_blog_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institute')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.relation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
