# Generated by Django 3.2.6 on 2022-04-26 15:29

import apps.blog.utils
import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_institute_institute_email'),
        ('portal', '0001_initial'),
        ('user', '0001_initial'),
        ('blog', '0003_alter_instituteblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteblog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.instituteuser'),
        ),
        migrations.AddField(
            model_name='instituteblog',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instituteblog',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute'),
        ),
        migrations.CreateModel(
            name='PortalBlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='portel/blog/default_logo.png', upload_to=apps.blog.utils.upload_blog_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.portalstaff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
