# Generated by Django 3.2.6 on 2021-09-29 11:38

import apps.core.validators
import apps.portal.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('profile_picture', models.ImageField(default='portal/profile/default_profile_picture.png', upload_to=apps.portal.utils.upload_portal_user_cover_image_to, validators=[apps.core.validators.ImageValidator()])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.portal')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffposition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
