# Generated by Django 3.2.6 on 2021-09-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='website',
            field=models.URLField(),
        ),
    ]
