# Generated by Django 3.2.6 on 2021-09-24 08:36

import apps.consultancy.utils
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0003_auto_20210922_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancystaff',
            name='profile_photo',
            field=models.ImageField(default='consultancy_staff/photo/default_logo.png', upload_to=apps.consultancy.utils.upload_consultancy_staff_image_to, validators=[apps.core.validators.ImageValidator()]),
        ),
    ]
