# Generated by Django 3.2.6 on 2021-09-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0004_consultancystaff_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancystaff',
            old_name='position',
            new_name='role',
        ),
    ]
