from apps import studentIdentity
from django.urls import path, include

# This file will contain all the end-points
urlpatterns = [
    path(
        '',
        include('apps.college.urls')
    ),
    path(
        'student/',
        include('apps.student.urls')
    ),
    path(
        'notification/',
        include('apps.notification.urls'),
    ),
    path(
        'students/',
        include('apps.students.urls')
    ),
    path(
        'consultancy/',
        include('apps.consultancy.urls')
    ),
    path(
        'institute/',
        include('apps.institute.urls')
    ),
    path(
        'institute_course/',
        include('apps.institute_course.urls')
    ),
    path(
        'auth/',
        include('apps.auth.urls')
    ),
    path(
        'staff/',
        include('apps.staff.urls')
    ),
    path(
        'portal/',
        include('apps.portal.urls')
    ),
    path(
        'setting/',
        include('apps.settings.urls')
    ),
    path(
        'troubleshooting/',
        include('apps.troubleshooting.urls')
    ),
    path(
        'schedule/',
        include('apps.schedule.urls')
    ),
    path(
        'blogs/',
        include('apps.blog.urls')
    ),
    path(
        'gallery/',
        include('apps.gallery.urls')
    ),
    path(
        'citizenship/',
        include('apps.studentIdentity.urls')
    )
]
