# Generated by Django 3.2.6 on 2022-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalessay',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentlor',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsop',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
