# Generated by Django 3.2.6 on 2021-11-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={},
        ),
    ]
