# Generated by Django 3.2.6 on 2021-10-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellingschedule',
            old_name='counsellor',
            new_name='counselor',
        ),
    ]
