# Generated by Django 3.2.6 on 2021-10-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_counsellor_counsellingschedule_counselor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.counsellingschedule'),
        ),
    ]
