# Generated by Django 3.2.6 on 2021-12-01 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0012_alter_completeprofiletracker_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('relation', models.CharField(choices=[('father', 'father'), ('mother', 'mother')], max_length=20)),
                ('fullname', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('annual_income', models.FloatField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
            options={
                'unique_together': {('student', 'relation')},
            },
        ),
    ]
