# Generated by Django 3.2.6 on 2021-12-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparents',
            name='annual_income',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
