# Generated by Django 3.2.6 on 2021-12-23 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_favouriteinstitute'),
        ('parentsDetail', '0002_alter_studentparents_annual_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparents',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentparents',
            name='country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentparents',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentparents',
            name='relation',
            field=models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('limited_information', 'limited_information')], max_length=20),
        ),
        migrations.CreateModel(
            name='Siblings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinLengthValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('maritial_status', models.CharField(choices=[('never_married', 'never_married'), ('seperated', 'seperated'), ('divorced', 'divorced'), ('widowed', 'widowed'), ('domestic_parents', 'domestic_parents')], max_length=100)),
                ('children', models.BooleanField(default=False)),
                ('no_of_childrents', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinLengthValidator(0)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
