# Generated by Django 3.2.6 on 2022-04-30 07:44

import apps.core.validators
import apps.gallery.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_institute_rating'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('approve', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='consultancy/logo/default_logo.png', upload_to=apps.gallery.utils.upload_gallery_image_to, validators=[apps.core.validators.ImageValidator()])),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='institute.institutestaff')),
            ],
            options={
                'db_table': 'institute_galleries',
            },
        ),
    ]
