# Generated by Django 3.2.6 on 2022-04-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_institutegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutegallery',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
