# Generated by Django 3.2.6 on 2021-09-29 11:38

import apps.student.utils.file_function
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=200)),
                ('duration', models.CharField(default='1', max_length=40)),
                ('level', models.CharField(max_length=200)),
                ('percentage', models.FloatField()),
                ('outof', models.IntegerField(default=100)),
                ('marksheet', models.FileField(upload_to=apps.student.utils.file_function.student_certificate)),
                ('certificate', models.FileField(upload_to=apps.student.utils.file_function.student_certificate)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_exam_name', models.CharField(blank=True, max_length=600, null=True)),
                ('score', models.IntegerField()),
                ('certificate', models.FileField(upload_to=apps.student.utils.file_function.student_certificate)),
            ],
        ),
        migrations.CreateModel(
            name='LORModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lor', models.FileField(blank=True, upload_to=apps.student.utils.file_function.student_certificate)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_type', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('relation', models.CharField(default='Father', max_length=200)),
            ],
        ),
    ]
