# Generated by Django 3.2.6 on 2021-10-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20211002_0849'),
        ('troubleshooting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshoot',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.portalstaff'),
        ),
    ]
