# Generated by Django 3.2.6 on 2021-11-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0002_consultancystaff_user'),
        ('troubleshooting', '0002_alter_troubleshoot_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshoot',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultancy.consultancystaff'),
        ),
    ]
